spring:
  application:
   name: report-exm
  profiles:
    default: default
  config:
    import: "configserver:http://localhost:7777"

server:
  servlet:
    context-path: /report-exm
  port: 7070

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
