spring:
  application:
    name: auth-server

  config:
    import: optional:configserver:http://localhost:7777

  datasource:
    url: jdbc:mysql://localhost:3309/auth_db
    username: authuser
    password: AuthJWT2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 3030
  servlet:
    context-path: /auth-server

eureka:
  instance:
    hostname: localhost  # 👈 fuerza a que use localhost
    prefer-ip-address: false
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
