spring:
  profiles:
    default: prod
  application:
    name: auth-server

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

server:
  port: 3030
  servlet:
    context-path: /auth-server

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"

  client:
    service-url:
      defaultZone: ${EUREKA_URL}
