spring:
  application:
    name: persona-ms

  profiles:
    default: default  # cambiar a prod para el instalador de dockerizar

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

  datasource:
    url: ${pe.url}
    username: ${pe.username}
    password: ${pe.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${pe.maximum-pool-size}
      connection-timeout: ${pe.connection-timeout}
    initialization-mode: always

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'

  web:
    resources:
      static-locations: file:img/
      add-mappings: true

logging:
  level:
    crip.persona.com.pe: INFO
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /persona-ms
  port: 0

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}