spring:
  application:
    name: oferta-ms

  profiles:
    default: default

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${db.maximum-pool-size}
      connection-timeout: ${db.connection-timeout}
    initialization-mode: always

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'

logging:
  level:
    crip.oferta.com.pe: INFO
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /oferta-ms
  port: 0

eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

db:
  url: jdbc:postgresql://localhost:5434/ofertas_db
  username: ofertas
  password: Of3rt4sM1cr0s3rv1c3
  maximum-pool-size: 5
  connection-timeout: 20000
