spring:
  application:
    name: oferta-ms

  profiles:
    default: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

  datasource:
    url: ${of.url}
    username: ${of.username}
    password: ${of.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${of.maximum-pool-size}
      connection-timeout: ${of.connection-timeout}
    initialization-mode: always

  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    crip.oferta.com.pe: INFO
    org.springframework.cloud.config.client: DEBUG
    org.springframework.cloud.bootstrap: DEBUG
    org.springframework.boot.context.config: DEBUG
    com.zaxxer.hikari: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /oferta-ms
  port: 8082

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}