spring:
  application:
    name: gateway

  profiles:
    active: oauth2  # Cambia entre: eureka-off, eureka-on, oauth2

server:
  port: 4040

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: ${EUREKA_URL}
