spring:
  application:
    name: gateway

  profiles:
    default: oauth2  # Cambia entre: eureka-off, eureka-on, oauth2

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 4040

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost         # 👈 fuerza uso de localhost
    prefer-ip-address: false    # 👈 importante: no usar IP ni nombre completo
    instance-id: ${spring.application.name}:${random.value}
