spring:
  application:
    name: practica-ms

  profiles:
    active: prod

  config:
    import: "optional:configserver:${CONFIG_SERVER_HOST}"

  datasource:
    url: ${pr.url}
    username: ${pr.username}
    password: ${pr.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${pr.maximum-pool-size}
      connection-timeout: ${pr.connection-timeout}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

server:
  port: 8083
  servlet:
    context-path: /practica-ms

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    crip.practica.com.pe: INFO
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: '*'