spring:
  profiles:
    active: prod
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Cocodrilodormilon123/practica-config.git
          default-label: main
          clone-on-start: true
          username: FENIXTTOBAN
          #password: ${GIT_TOKEN}
          password: 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

server:
  port: 7777

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
